url: http://lukemartin.github.io
auto: no
server: no
include: js
exclude: CNAME config.rb Gruntfile.js node_modules package.json README.md luke.is.v4.sublime-project luke.is.v4.sublime-workspace
permalink: /blogging/:year/:month/:day/:title